version: "3"
services:
  api:
    build: ./api
    image: ${DOCKER_REGISTRY}
    container_name: get-paid-api
    env_file: .env
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    links:
      - db
  db:
    build: ./db
    image: postgres:latest
    container_name: get-paid-db
    env_file: .env
    ports:
      - 5432:5432
