version: "3"
services:
  api:
    build: ./api
    image: 277625601220.dkr.ecr.us-east-1.amazonaws.com/get-paid
    container_name: get-paid-api
    env_file: .env
    environment:
      - NODE_ENV=production
      - PORT=80
    ports:
      - 80:80
      - 3000:3000
    links:
      - db
  db:
    build: ./db
    image: postgres:latest
    container_name: get-paid-db
    env_file: .env
    ports:
      - 5432:5432
