#!/bin/sh
set -e

rm -rf dist
mkdir -p dist

bundle exec jekyll build

cd ./functions/origin-request
yarn install --production
yarn setup
zip -r ../../dist/origin-request-function.zip index.js node_modules/
cd ../..
