#!/bin/sh
set -e

docker ps -q --filter ancestor="dwmkerr/dynamodb" | xargs docker stop
docker run -p 8000:8000 dwmkerr/dynamodb:latest -sharedDb &

cd dynamo
yarn && yarn start
cd ..

cd graphapi
yarn && yarn start
cd ..
